local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 30.0
   publish_frequency: 30.0
   width: 5.0 #was 20, shouldnt this be maxed out by the obstacle_range
   height: 5.0 #was 20, shouldnt this be maxed out by the obstacle_range
   resolution: 0.05
   static_map: false
   rolling_window: true
